package com.yadony.api.matching.dto;

import com.yadony.api.matching.PricingMode;
import com.yadony.api.matching.TripRecurrenceStatus;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.List;
import java.util.UUID;

public record TripRecurrenceDto(
        UUID id,
        UUID sourceTemplateId,
        String departureCity,
        String arrivalCity,
        String transportMode,
        String capacityUnit,
        Double availableKg,
        Double pricePerKg,
        PricingMode pricingMode,
        boolean negotiable,
        String currency,
        String description,
        List<String> acceptedCategories,
        List<String> refusedCategories,
        AddressDto pickupAddress,
        AddressDto deliveryAddress,
        LocalTime departureTime,
        LocalTime arrivalTime,
        boolean cashAccepted,
        String weekdays,
        Integer horizonDays,
        LocalDate startDate,
        LocalDate endDate,
        Integer weekInterval,
        Integer publicationLeadDays,
        Integer handoverLeadDays,
        boolean active,
        LocalDate lastGeneratedDate,
        String lastPublicationErrorCode,
        String lastPublicationErrorMessage,
        LocalDateTime lastPublicationErrorAt,
        TripRecurrenceStatus status,
        LocalDate nextDepartureDate,
        LocalDate nextPublicationDate,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
) {}
