global:
  scrape_interval: 30s
  evaluation_interval: 30s
rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  # API et métriques VPS sont scrappées par Alloy puis envoyées à Prometheus
  # local via remote_write. Cela permet aussi de les envoyer à Grafana Cloud.

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
