#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# yadony k6 load-test runner
# ---------------------------------------------------------------------------
# Usage: bash load-test/run.sh
# Prerequisites: k6 installed, BASE_URL exported (staging/dev ONLY).
# ---------------------------------------------------------------------------

# PROD GUARD — refuse to run against production or empty BASE_URL
if [[ -z "${BASE_URL:-}" ]]; then
  echo "REFUS: BASE_URL est vide — exporter l'URL de staging avant de lancer les tests." >&2
  exit 1
fi

if [[ "${BASE_URL}" == *"api.yadony.app"* ]]; then
  echo "REFUS: prod/empty BASE_URL interdite — BASE_URL contient api.yadony.app." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Run scenarios
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPORTS_DIR="${SCRIPT_DIR}/reports"
mkdir -p "${REPORTS_DIR}"

SCENARIOS=("read_endpoints" "favorites" "bid_journey")

for scenario in "${SCENARIOS[@]}"; do
  echo ""
  echo "==> Running scenario: ${scenario}"
  k6 run \
    --env BASE_URL="${BASE_URL}" \
    --env FIREBASE_API_KEY="${FIREBASE_API_KEY:-}" \
    --env K6_TEST_EMAIL="${K6_TEST_EMAIL:-}" \
    --env K6_TEST_PASSWORD="${K6_TEST_PASSWORD:-}" \
    --env FAV_TRIP_ID="${FAV_TRIP_ID:-}" \
    --env BID_SEARCH_DEPARTURE="${BID_SEARCH_DEPARTURE:-}" \
    --env BID_SEARCH_ARRIVAL="${BID_SEARCH_ARRIVAL:-}" \
    --env BID_WEIGHT_KG="${BID_WEIGHT_KG:-}" \
    --env REPORTS_DIR="${REPORTS_DIR}" \
    --summary-export="${REPORTS_DIR}/${scenario}.json" \
    "${SCRIPT_DIR}/scenarios/${scenario}.js"
done

# ---------------------------------------------------------------------------
# Aggregate: emit reports/load-report.md
# ---------------------------------------------------------------------------
REPORT="${REPORTS_DIR}/load-report.md"
echo "==> Aggregating results into ${REPORT}"

cat > "${REPORT}" << 'HEADER'
# yadony Load-Test Report

Generated by `load-test/run.sh`.

| Scenario | p95 (ms) | p99 (ms) | RPS | Error rate |
|----------|----------|----------|-----|------------|
HEADER

if command -v jq &>/dev/null; then
  # jq path: parse k6 --summary-export JSON
  for scenario in "${SCENARIOS[@]}"; do
    JSON="${REPORTS_DIR}/${scenario}.json"
    if [[ -f "${JSON}" ]]; then
      p95=$(jq -r '.metrics.http_req_duration.values["p(95)"] // "N/A"' "${JSON}" 2>/dev/null || echo "N/A")
      p99=$(jq -r '.metrics.http_req_duration.values["p(99)"] // "N/A"' "${JSON}" 2>/dev/null || echo "N/A")
      rps=$(jq -r '.metrics.http_reqs.values.rate // "N/A"' "${JSON}" 2>/dev/null || echo "N/A")
      err=$(jq -r '.metrics.http_req_failed.values.rate // "N/A"' "${JSON}" 2>/dev/null || echo "N/A")
      # Round to 2 decimal places if numeric
      p95=$(echo "${p95}" | awk '{if ($1~/^[0-9]/) printf "%.2f", $1; else print $1}')
      p99=$(echo "${p99}" | awk '{if ($1~/^[0-9]/) printf "%.2f", $1; else print $1}')
      rps=$(echo "${rps}" | awk '{if ($1~/^[0-9]/) printf "%.2f", $1; else print $1}')
      err=$(echo "${err}" | awk '{if ($1~/^[0-9]/) printf "%.4f", $1; else print $1}')
      echo "| ${scenario} | ${p95} | ${p99} | ${rps} | ${err} |" >> "${REPORT}"
    else
      echo "| ${scenario} | (no data) | (no data) | (no data) | (no data) |" >> "${REPORT}"
    fi
  done
elif command -v node &>/dev/null; then
  # node fallback: same extraction via JSON.parse
  node - "${SCENARIOS[@]}" "${REPORTS_DIR}" << 'NODE'
const fs = require('fs');
const path = require('path');
const scenarios = process.argv.slice(2, process.argv.length - 1);
const reportsDir = process.argv[process.argv.length - 1];
const reportPath = path.join(reportsDir, 'load-report.md');

for (const scenario of scenarios) {
  const jsonPath = path.join(reportsDir, `${scenario}.json`);
  if (!fs.existsSync(jsonPath)) {
    fs.appendFileSync(reportPath, `| ${scenario} | (no data) | (no data) | (no data) | (no data) |\n`);
    continue;
  }
  const data = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
  const dur = data.metrics && data.metrics.http_req_duration && data.metrics.http_req_duration.values;
  const p95 = dur ? (dur['p(95)'] || 'N/A').toString().replace(/(\.\d{2})\d+/, '$1') : 'N/A';
  const p99 = dur ? (dur['p(99)'] || 'N/A').toString().replace(/(\.\d{2})\d+/, '$1') : 'N/A';
  const rps = data.metrics && data.metrics.http_reqs ? (data.metrics.http_reqs.values.rate || 'N/A') : 'N/A';
  const err = data.metrics && data.metrics.http_req_failed ? (data.metrics.http_req_failed.values.rate || 'N/A') : 'N/A';
  fs.appendFileSync(reportPath, `| ${scenario} | ${p95} | ${p99} | ${rps} | ${err} |\n`);
}
NODE
else
  # Fallback: concatenate raw JSON with a note
  {
    echo ""
    echo '> Note: `jq` and `node` not found — raw JSON summaries below.'
    echo ""
    for scenario in "${SCENARIOS[@]}"; do
      JSON="${REPORTS_DIR}/${scenario}.json"
      echo "## ${scenario}"
      echo '```json'
      if [[ -f "${JSON}" ]]; then
        cat "${JSON}"
      else
        echo "(no data)"
      fi
      echo '```'
      echo ""
    done
  } >> "${REPORT}"
fi

echo ""
echo "==> Done. Report written to: ${REPORT}"
