apiVersion: 1

contactPoints:
  - orgId: 1
    name: Telegram
    receivers:
      - uid: telegram-yadony
        type: telegram
        settings:
          bottoken: $__env{TELEGRAM_BOT_TOKEN}
          chatid: $__env{TELEGRAM_CHAT_ID}
          message: |-
            🔔 {{ .CommonLabels.alertname }}
            Statut : {{ .Status }}
            {{ range .Alerts }}{{ .Annotations.summary }}
            {{ end }}
          parse_mode: none
        disableResolveMessage: false
